#!/usr/bin/env bash
# Debug and configure Nginx to listen on port 80

# Remove the default Nginx configuration
rm -f /etc/nginx/sites-enabled/default

# Create a symbolic link to the default Nginx configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service
service nginx restart
