#!/usr/bin/env bash

# Configures Nginx to listen on port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart

# Truncate the nginx.pid file
truncate -s 0 /run/nginx.pid
